### ISSUE TITLE
? No movie releases have XXX covers  (latest master)

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#1804]
No movie releases have XXX covers.
This might mean the Administrator's has file permission issues, or he has disabled looking up XXX covers.
This could also mean there are no movie releases.
Please try looking in the list view, which does not require XXX covers. 

Settings: Lookup XXX: 	Yes

Whether to attempt to lookup film information from ADE or Popporn.

XXX Movie List

No XXX Movies available.

Although releases are being created and have sample JPG's, previews etc etc. i do not see any covers being created or lookup's being performed.

**Comment by Sweepr** [comment]
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0007 sec)
SELECT *
FROM `xxxinfo`
LIMIT 0 , 30

**Comment by Sweepr** [comment]
# [~/public_html/nZEDb/misc/testing/PostProcess]# php updateXXXImages.php true
0 covers set.
0 backdrops set.
0 movies unset.

# [~/public_html/nZEDb/misc/testing/PostProcess]# php getXXXCovers.php
Updating 0 movie covers.

**Comment by Sweepr** [comment]
# [~/public_html/nZEDb/cli]# php versions.php
Leaving tag version at 0.4.23Version info in file:
  Commit:
SQL   DB: 357
SQL File: 357
     Tag: 0.4.23

# [~/public_html/nZEDb/cli]# php update_db.php true
Db updater starting ...
Looking for unprocessed patches...
Info: Nothing to patch, you are already on version 357

**Comment by niel** [comment]
I just tested this on dev branch and it seems to be working fine. So chances are: 
1) it was fixed recently and hasn't made it to master branch yet,
2) there is nothing in your DB that can be updated,
3) a configuration problem.

**Comment by Sweepr** [comment]
Hello niel,

1) pulled latest master yesterday
2) There are releases in DB from which i know for sure they are movies which were in cover view on my previous nZEDb instance.
3) This could be., but i double checked all today and cannot find anything.

So it quite weird, other releasedshave samples, jpg's.

Could this have something todo with Nfo ?

**Comment by Sweepr** [comment]
Yesterday i switched to DEV branch, it's running fine using Tmux, collecting parts, binaries, collections, creating releases, renaming, predb scraping, post processing, samples, JPG's all that kind of stuff, but no movie releases. ?

I have absolutly no clue to what's wrong here.

**Comment by Atmos01** [comment]
It seems i have the same problem.. I got a lot of releases but not all releases are coming up.. I got 250 xxx releases and only 5 that with covers.. (there are covers when you go to: /admin/xxx-list.php)
i miss alot of releases in the overview, not only xxx..

**Comment by Sweepr** [comment]
I still do not see anything coming up in coverview.  listview is fine.. is see JPG and Samples created but no covers being picked up.

Looks like some kind of config error maybe but can someone help me figure out what's wrong ?

**Comment by Sweepr** [comment]
*Is there somekind of way i can manually trigger a XXX release using a setting in the database for processing covers ?

**Comment by Atmos01** [comment]
You could try: 

php postprocess.php xxx true

**Comment by Sweepr** [comment]
@Atmos01 

That worked, why isn't that script run bij Tmux?

**Comment by Bart39** [comment]
@Sweepr - it is if you have lookup XXX switched on in site settings

**Comment by Sweepr** [comment]
Well it is enabled, but did not trigger for some kind of reason.

Manually running the script fill's up the cover view now.

![untitled](https://cloud.githubusercontent.com/assets/2857865/9291363/5c04a42a-43ba-11e5-892e-d8d2219cf0c3.png)

**Comment by Sweepr** [comment]
PS i'm on DEV branch , earlier on Master but there is had the same problem.

**Comment by Bart39** [comment]
when xxx lookups were added for unknown reasons they run in the amazon pane so you need to make sure you have postprocess amazon turned on in tmux as well

**Comment by Sweepr** [comment]
Do you mean these settings?

![untitled](https://cloud.githubusercontent.com/assets/2857865/9291382/9f1bdf6a-43bc-11e5-9351-45c89be60b91.png)

All seem to be enabled

**Comment by Sweepr** [comment]
Ah found in Tmux settings pane.

![untitled](https://cloud.githubusercontent.com/assets/2857865/9291393/fa562124-43bc-11e5-863a-694791945fc8.png)

Postprocess Amazon: was set to No.

Turned to on and restarted the Tmux, let's see what happens now.

**Comment by Atmos01** [comment]
I got everything working now except Consoles :S 
I had the same setting off btw , just switched it on..lets see what happens..

**Comment by Sweepr** [comment]
Left it running for 10 hours now, but no extra covers were added after switching this ON.

Now running the script manually added covers immediatly

**Comment by Sweepr** [comment]
@Bart39, I just checked and turns out i did not save the Amazon process setting, it was still set to NO, so i will give it another try

**Comment by Sweepr** [comment]
Postprocess Amazon/XXX:
