### ISSUE TITLE
XML Parsing issue on newest stable 0.x

### ISSUE THREAD

**Issue by ialexpw** [nZEDb/nZEDb#2198]
### Expected behaviour

API to continue as usual.
### Actual behaviour

Receiving parsing errors as below;

XML Parsing Error: not well-formed
Location: https://xx/api?t=caps
Line Number 1, Column 1:
[38;5;010mUpdating tag version to [0m[38;5;011mv0.6.1.2[0m<?xml version="1.0" encoding="UTF-8"?>

On every API search - this has also meant I can no longer see/search any NZBs on the site. 
### Steps to reproduce the behaviour

Just updated to latest stable this morning.

**Comment by Wally73** [comment]
are you sure you're on 0.6.2? as it works fine here

**Comment by ialexpw** [comment]
Just ran this morning;

Checking database version...
Db: 445,        File: 445
Up to date.

**Comment by Wally73** [comment]
latest 0.x is updated a good hour ago

**Comment by DariusIII** [comment]
0.6.2 was pushed an hour or so ago.

**Comment by ialexpw** [comment]
I only ran the update ~15 minutes ago to get the above

**Comment by Wally73** [comment]
according to page source view you're still on <caps>
 <server appversion="v0.6.1.2" not on v0.6.2

**Comment by ialexpw** [comment]
Odd - any reason why the update wouldn't overwrite this? Or the best way to force an update?

**Comment by niel** [comment]
try doing 'git pull' then running ./zed update nzedb again.

**Comment by ialexpw** [comment]
Getting the below now, with the new version;

XML Parsing Error: not well-formed
Location: https://xx/api?t=caps
Line Number 1, Column 1:[38;5;010mUpdating tag version to [0m[38;5;011mv0.6.2[0m<?xml version="1.0" encoding="UTF-8"?>
^

**Comment by niel** [comment]
Try updating again.

**Comment by ialexpw** [comment]
XML Parsing Error: not well-formed
Location: https://xx/api?t=caps
Line Number 1, Column 1:[38;5;010mUpdating tag version to [0m[38;5;011mv0.6.2.1[0m<?xml version="1.0" encoding="UTF-8"?>
^

Did a git pull then ./zed update nzedb - getting the above

**Comment by niel** [comment]
Which theme are you using?

**Comment by ialexpw** [comment]
Currently using Alpha

**Comment by niel** [comment]
For the time being, as no one reported this problem during dev testing, I recommend you revert to previous version while we investigate this.
To revert do:
git reset v0.6.1.2
composer install

**Comment by ialexpw** [comment]
This is odd - I'm still getting it after reverting... (but with the previous version). Even though the problem only came in after updating

XML Parsing Error: not well-formed
Location: https://xx/api?t=caps
Line Number 1, Column 1:[38;5;010mUpdating tag version to [0m[38;5;011mv0.6.1.2[0m<?xml version="1.0" encoding="UTF-8"?>
^

**Comment by niel** [comment]
It's sounding more and more like the problem is local to your particular setup.

**Comment by ialexpw** [comment]
It's very strange - I've got a mirrored setup on the same server where the API works (not updated/played around with this one). Trying to find what could have caused this to appear..

**Comment by ghost** [comment]
I had this exact problem as well. Comes from: https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/utility/Versions.php#L160

Reverted back to previous release for now. I did do git pull manually by accident, was used to doing that :P So maybe ./zed update all does extra things besides composer, git pull and DB update.

**Comment by ialexpw** [comment]
Glad it's not just me (..in a way ;-)) - I reverted back also for now

**Comment by niel** [comment]
@Fossil01 While you are correct that the erroneous text is from that line, it is not the cause of the problem (at least directly). That line has existed for many months without a problem and this problem is not showing up for any but a very small proportion of users.
Currently I'm in the process of refactoring the Versions code to use the newer class in the Lithium code instead of that older class.

**Comment by ghost** [comment]
@niel I checked the history and saw it was indeed "old". Nonetheless I commented that out at first to try to get my API working again but then I got other errors so restored from backup.

**Comment by stuartst** [comment]
Same issue for me.

Resolved for short term by commenting out the echo statement on line 161 in file:

`/nzedb/utility/Versions.php`

**Comment by bobtongue** [comment]
I also have this issue after updating. RSS is no longer working.
 Sonarr was failing to connect with this error, An error occurred while processing feed. http://myserver.com/api?t=tvsearch&cat=5010,5030,5040,5050,5080&extended=1&apikey=(removed)&offset=0&limit=100: '', hexadecimal value 0x1B, is an invalid character. Line 1, position 1.
 I did comment out that echo statement as stuartst did and I now get results from rss and sonarr seems happy. Seems /nzedb/utility/Versions.php created some problems besides tmux not starting.

**Comment by stevenmcastano** [comment]
This appears to be the same errors I was getting when RSS went nuts on me after the update, then the API calls from Sonarr and CouchPotato stopped working as well.

**Comment by bobtongue** [comment]
Just FYI, after the latest fix for tmux, this is still broken. Commenting out the echo statement in line 161 still resolves the issue, for now.

**Comment by ialexpw** [comment]
The above for me allows the API to work, but does not fix the web listings for me. Showing I have no releases.

**Comment by malanden** [comment]
I too had the exact same issue at bobtongue reported, and so did my users. Commenting out line 161 in /nzedb/utility/Versions.php seems to have been a short term fix. Seems being the key word.

**Comment by niel** [comment]
This should be fixed with the latest release (v0.6.2.4).

**Comment by bobtongue** [comment]
Updated, Uncommented line 161, Confirmed fixed on 0.x. Thanks niel

**Comment by ialexpw** [comment]
I understand this seems to be unique to me, but since updating I can no longer run tmux and I also get no release listings?

When I run tmux I get "Monitor encountered severe errors receiving process data from mysql. Please diagnose and try running again"

If I go back I can get it working, it's just after updating... any ideas of what could cause this?

**Comment by bobtongue** [comment]
Did you check for corruption in your database?

**Comment by niel** [comment]
@ialexpw sounds like your current issue is unrelated to the original one. The XML related issues were fixed and released to stable a few days back.
If you can show this is a new issue (not a database problem as the message above shows), please create a new issue.
