### ISSUE TITLE
/apit=get&id= returns blank page

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2226]
URLs like these https://URL/api?apikey=REMOVED&t=get&id=c0037d1c460cb3a6ad9d45b8c7c2017f45d464e9 which are called by Mylar for example only return a blank page / empty HTTP200 response. The ID is correct and exists.

I have tested this against a NNTmux indexer on which is works properly. Anyone running latest 0.x who has this issue too?

**Comment by ghost** [comment]
Duplicate of #2218 apparently.

**Comment by ghost** [comment]
Found an error when loading this page:

```
PHP message: PHP Notice:  Undefined index: ep in nzedb/www/pages/api.php on line 164
```

**Comment by DariusIII** [comment]
Fixed in dev in commit 23e637c4e7833d2b94ddd724bd89328c7b50ac5c

**Comment by ghost** [comment]
That's another issue i think :P The TV case where your fix is should never be called when downloading a NZB I think.

**Comment by ghost** [comment]
Okay so looks like there's missing a case in api.php as the case 'g' is present in the original NN code. When I pasted that code into api.php everything works fine.

https://github.com/kop1/newznab/blob/master/www/pages/api.php#L256

[Edit] This fix is already in dev. Didn't notice that before.

Still getting the Undefined index: ep though but @DariusIII his fix will probably fix that.
