### ISSUE TITLE
Empty NZB when grabbing

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2387]
###Expected behaviour
nzb download capability

###Actual behaviour
empty nzb download since latest patch

![image](https://cloud.githubusercontent.com/assets/3989347/22865571/ecf8282a-f134-11e6-9dc0-4a23aaed4668.png)

###Steps to reproduce the behaviour
1) after latest patch, go to TV Poster Wall
2) send somethign to your queue
3) check SABNZB or nzbget... see the above issue.

Version
Looking up Git tag version(s)
Hash: d94bf9d36a45f87dd52231944a538eff691e0886
XML version: 0.0.0-dev
Git version: 0.6.9.0
Looking up SQL patch version(s)
XML version: 471
 DB version: 471

**Comment by niel** [comment]
Is this still a problem with latest dev?

**Comment by dilbaggins** [comment]
yes.

Looking up Git tag version(s)
Hash: 01ebc85eb2bd5966ad38b2404683a4b6b42e0379
XML version: 0.0.0-dev
Git version: 0.6.9.0
Looking up SQL patch version(s)
XML version: 471
 DB version: 471

**Comment by niel** [comment]
Can you be more specific about when this happened. We've had very few merges this last week, and only one major one.

**Comment by dilbaggins** [comment]
sure @niel i updated to the new TPG mandatory dev patch that came out and this started occuring along with the releases/tmux being out of synch which is the other issue i commented on.

i have always used TPG so unaware of what the issue is.

**Comment by niel** [comment]
I mean which day, so I can try to narrow the cause down. In UTC time please ;-)

**Comment by DariusIII** [comment]
As far as i know there is no mandatory TPG patch, yet.

**Comment by dilbaggins** [comment]
02/08 @niel 

apologies @DariusIII 

meant this one:

2017-02-13 niel
	Mrg: dev-log-bad-regex branch. This adds logging of failed (as in errors, not zero results)
		regexes to the nZEDb log. **NOTE** This surpresses warning messages in the PHP log.
2017-02-12 b3rs3rk
	Chg: Improve performance by doing poster check in PHP instead of single row MySQL queries
2017-02-10 b3rs3rk
	Fix: Settings issues with AniDB population preventing run.
2017-02-10 DariusIII
	Fix: Search by reqid link in predb.tpl (fixes issue #2381)
2017-02-09 niel
	Mrg: dev-base-template-mod branch. See commit 2017-01-18.
	**Mrg: PR 2379, from kaibosh - Update sequential scripts for mandatory TPG use.**
**2017-02-08 niel
	Mrg: dev-mgr (MultiGroup Releases) branch into dev. This adds new feature for matching releases
		spread across several groups.**

**Comment by DariusIII** [comment]
As i am the one involved in the bold part, along with @b3rs3rk we have not encountered this behaviour (only on start, but that was solved) so we would need some kind of error logs. If you could send us a pastebin of that empty nzb it would help.

**Comment by dilbaggins** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nzb
PUBLIC "-//newzBin//DTD NZB 1.1//EN"
       "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">

<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
  <head>
    <meta type="category">Movies &gt; SD</meta>
    <meta type="name">(????) [00/45] - &quot;20th.Century.Women.2016.DVDScr.HebSubs.XviD.AC3-CM8.nzb&quot; yEnc</meta>
  </head>
</nzb>

**Comment by dilbaggins** [comment]
http://pastebin.com/HvfFXPUf

**Comment by DariusIII** [comment]
Is every nzb on site empty or just some?

**Comment by dilbaggins** [comment]
just the ones since the patch.  also i have to access the TV WALL to see any new releases.  the normal browse to "browse?t=5000" still shows the ones from 2.9 days ago when i patched.  (see the other issue i tagged you in also me)

**Comment by DariusIII** [comment]
Your missing releases issue are related to malformed nzbs. Does your PPA pane report bad or missing nzbs? Can you enable all the debugging options in settings.php?

**Comment by dilbaggins** [comment]
the PPA pane is showing no bad or missing nzbs?  i enabled debugging but not sure where to look for additional data points,

**Comment by DariusIII** [comment]
Have you maybe added posters to multigroup posters?

**Comment by dilbaggins** [comment]
@DariusIII no all i did was patch to latest dev. and this started occurring.. also
can i revert somehow?  lost two days now and want to get caught up.

**Comment by Bart39** [comment]
Check php_errors and also /resources/nzedb.log for any relevant errors

**Comment by dilbaggins** [comment]
@niel seeing a ton of these in php_cli_errors:
![image](https://cloud.githubusercontent.com/assets/3989347/22903508/d73c394a-f206-11e6-94ed-ff5500b8ddd1.png)

**Comment by dilbaggins** [comment]
![image](https://cloud.githubusercontent.com/assets/3989347/22903535/f56c4ed2-f206-11e6-8aa1-ca40725ad04a.png)

**Comment by niel** [comment]
That is strange, and shouldn't happen. I'll look into it

**Comment by dilbaggins** [comment]
@niel heres the stack trace (and for others)
http://pastebin.com/xbCdbMLY

**Comment by ThePeePs** [comment]
I too am have the same problem after puling yesterday, and updating.

I'm also getting nzb files that look exactly the same, with no segment or file sections.
```
[17-Feb-2017 12:24:53 US/Eastern] PHP Warning:  Error while sending QUERY packet. PID=1019 in /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php on line 404
[17-Feb-2017 12:24:53 US/Eastern] PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException' with message 'SELECT `Settings`.`value`, `Settings`.`hint` FROM `settings` AS `Settings` WHERE `Settings`.`name` = 'title' AND `Settings`.`subsection` = 'main' AND `Settings`.`section` = 'site';: MySQL server has gone away' in /var/www/nZEDb/libraries/lithium/data/source/Database.php:1604
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /var/www/nZEDb/libraries/lithium/data/source/Database.php(1605): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_error', Array, Object(Closure))
#2 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(406): lithium\data\source\Database->_error('SELECT `Setting...')
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/M in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 1604
```

**Comment by kaibosh** [comment]
i had 55 of those "empty" nzbs generated in the same minute when (or just after) i last upgraded 0.x, no new ones created since then.

`find resources/nzb/ -type f -size -400c -exec ls -l {} \;`

**Comment by ThePeePs** [comment]
This is the way I removed them.  It's just a quick check to make sure it's really an empty nzb, and deletes it, if it is.
````
find resources/nzb/ -type f -size -470c  -exec sh -c 'test=$(zcat {} | grep segment -c); if [ $test -eq 0 ]; then rm {};fi' \;
````

**Comment by ThePeePs** [comment]
The fix for me thus far, as been moving to new hardware.  Since the move, there hasn't been any new empty nzb's created. Tho I also haven't re-updated the code and db patches yet.  At some point this week, I'll setup a testing VM and see if I'm able to re-produce the problem.

**Comment by eroth312** [comment]
I'm experiencing this same issue.  It looks like every time the script to create releases runs, I'm getting a bunch of similar errors in my log (an example below, but they're all the same).

It had occurred for me on 0.6.9.0. I switched to the dev branch in hope of getting a fix, but it's still occurring.  It's a big problem, as there are a mess of empty nzb's getting created.


[02-Mar-2017 22:29:01 America/Chicago] PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException' with message 'DESCRIBE `models`: Table 'nzedb.models' doesn't exist' in /var/www/nZEDb/libraries/lithium/data/source/Database.php:1604
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /var/www/nZEDb/libraries/lithium/data/source/Database.php(1605): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_error', Array, Object(Closure))
#2 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(406): lithium\data\source\Database->_error('DESCRIBE `model...')
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(409): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_execute', Array, Object(Closure))
#5 /var/www/nZEDb/libraries in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 1604

**Comment by niel** [comment]
@eroth312 We never determined the cause of the issue. Reverting to v0.6.9.0, after fixing some broken files, restored behaviour and that's what I suggest you do.
It was probably the broken files that was the problem in the first place, but there's no way to be sure.

**Comment by eroth312** [comment]
@niel What do you mean by fixing broken files?  The empty nzb's themselves, or something else within the codebase?

**Comment by niel** [comment]
Files that were not correctly updated by previous git pull, so "something else within the codebase".

**Comment by eroth312** [comment]
Ok, thanks.  I'll give it a shot and report back.

**Comment by eroth312** [comment]
I've gone ahead and freshly installed everything to a new directory, and I'm still getting the same issue with empty NZB's and the exact same error quoted above in the php_errors log.
It seems like all NZBs created by the tmux process are empty, but if I run the multithreaded php script myself, it does have a bunch of successes (haven't verified everything, but haven't found empty ones).  Is there potentially something amok with my tpg configuration that tmux is looking at?

**Comment by niel** [comment]
I do not know what else to suggest, as this seems to be only you suffering this particular problem.
